# This is a basic workflow to help you get started with Actions

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to cPanel FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # local-dir: <local github folder -- use ./ for repository root>
        local-dir: ./
        # server-dir: <remote_dir -- use / for root>
        server-dir: /
        protocol: ftps
        security: strict
        dry-run: false
